"use client";
import React, { createContext, useContext, useState, useEffect } from "react";

export type Lang = "en" | "ar";

export const translations = {
  en: {
    nav: {
      home: "Home",
      browseHalls: "Browse Halls",
      about: "About",
      contact: "Contact",
      login: "Login",
      getStarted: "Get Started",
      lang: "العربية",
    },
    hero: {
      badge: "Algeria's Premier Venue Platform",
      title1: "Celebrate Life's Most",
      title2: "Precious Moments",
      desc: "Discover and book Algeria's finest luxury event halls for weddings, celebrations, and unforgettable occasions.",
      exploreHalls: "Explore Halls",
      listVenue: "List Your Venue",
    },
    featured: {
      badge: "Top Picks",
      title: "Featured Luxury Venues",
      noVenues: "No venues available yet.",
      guests: "guests",
      perEvent: "per event",
      viewDetails: "View Details",
      seeAll: "See All Venues →",
    },
    howItWorks: {
      badge: "Simple Process",
      title: "How It Works",
      steps: [
        {
          title: "Browse & Discover",
          desc: "Explore our curated collection of luxury event halls across Algeria",
        },
        {
          title: "Compare & Select",
          desc: "Review details, pricing, availability and guest capacity",
        },
        {
          title: "Book & Celebrate",
          desc: "Secure your venue and celebrate your most special day",
        },
      ],
    },
    whyChoose: {
      badge: "Why Afrahi",
      title: "Why Choose Afrahi",
      features: [
        {
          title: "Curated Selection",
          desc: "Handpicked luxury venues that meet our highest standards for elegance and service",
        },
        {
          title: "Instant Booking",
          desc: "Book your perfect venue instantly with our streamlined reservation system",
        },
        {
          title: "Transparent Pricing",
          desc: "Clear, upfront pricing with no hidden fees or surprises",
        },
        {
          title: "Expert Support",
          desc: "Dedicated support to help you plan the perfect celebration",
        },
      ],
    },
    stats: {
      luxuryVenues: "Luxury Venues",
      happyClients: "Happy Clients",
      eventsHosted: "Events Hosted",
      citiesCovered: "Cities Covered",
    },
    testimonials: {
      badge: "Testimonials",
      title: "What Our Clients Say",
      reviews: [
        {
          name: "Amina Benali",
          role: "Bride",
          init: "A",
          quote:
            "Afrahi made our wedding day perfect! The booking process was seamless and the venue exceeded our expectations.",
        },
        {
          name: "Sofiane Toumi",
          role: "Corporate Event Manager",
          init: "S",
          quote:
            "Professional service and stunning venues. Our annual gala was a huge success thanks to Afrahi.",
        },
        {
          name: "Malika Cherif",
          role: "Event Planner",
          init: "M",
          quote:
            "The platform is intuitive and the venues are top-notch. Highly recommend for any special occasion!",
        },
      ],
    },
    readyToBook: {
      badge: "Get Started Today",
      title: "Ready to Book Your Dream Venue?",
      desc: "Join thousands of satisfied clients who trusted us with their most special moments",
      exploreHalls: "Explore Halls",
      createAccount: "Create Account",
    },
    footer: {
      desc: "Luxury event hall booking platform for weddings, celebrations and unforgettable moments in Algeria.",
      quickLinks: "Quick Links",
      contact: "Contact",
      rights: "© 2026 Afrahi. All rights reserved.",
      links: [
        { label: "Home", href: "/" },
        { label: "Browse Halls", href: "/browse-halls" },
        { label: "About", href: "/about" },
        { label: "Contact", href: "/contact" },
        { label: "Login", href: "/login" },
      ],
    },
    about: {
      hero: {
        badge: "Our Story",
        title: "About Afrahi",
        desc: "Your trusted partner for luxury event hall bookings in Algeria",
      },
      story: {
        badge: "Who We Are",
        title: "Our Story",
        p1: "Afrahi was founded with a simple mission: to make finding and booking the perfect luxury event hall effortless.",
        p2: "We understand that your special moments deserve exceptional venues, and we're here to connect you with Algeria's finest event spaces.",
      },
      mission: {
        title: "Our Mission",
        text: "To simplify the event planning process by providing a curated selection of premium venues, transparent information, and seamless booking experiences for every celebration.",
      },
      vision: {
        title: "Our Vision",
        text: "To become Algeria's leading platform for event venue discovery, setting the standard for luxury, reliability, and innovation in the event industry.",
      },
      values: {
        badge: "What We Stand For",
        title: "Our Values",
        subtitle: "The principles that guide everything we do",
        items: [
          {
            title: "Excellence",
            desc: "We maintain the highest standards in every venue we feature",
          },
          {
            title: "Trust",
            desc: "Transparent pricing and honest service you can rely on",
          },
          {
            title: "Innovation",
            desc: "Continuously improving our platform for better user experience",
          },
        ],
      },
      stats: {
        happyClients: "Happy Clients",
        eventsHosted: "Events Hosted",
        yearsExperience: "Years Experience",
        partnerVenues: "Partner Venues",
      },
      cta: {
        title: "Ready to find your perfect venue?",
        desc: "Join thousands of happy clients who found their dream event space with Afrahi.",
        getStarted: "Get Started",
        contactUs: "Contact Us",
      },
    },
    contact: {
      hero: {
        badge: "We're Here For You",
        title: "Get in Touch",
        desc: "Have questions about a venue or need help planning your event? Our team is here to assist you every step of the way.",
      },
      form: {
        badge: "Contact Us",
        title: "Send Us a Message",
        desc: "Fill out the form below and our team will get back to you within 24 hours.",
        firstName: "First Name",
        firstNamePh: "Enter your first name",
        lastName: "Last Name",
        lastNamePh: "Enter your last name",
        email: "Email Address",
        emailPh: "youremail@example.com",
        phone: "Phone Number",
        phonePh: "+213 --- --- ---",
        message: "Your Message",
        messagePh: "How can we help you?",
        send: "Send Message",
      },
      info: {
        phone: "Phone",
        email: "Email",
        office: "Office",
        workingHours: "Working Hours",
        officeAddress1: "123 Didouche Mourad Street",
        officeAddress2: "Algiers 16000, Algeria",
        hours1: "Sunday–Thursday: 9AM–6PM",
        hours2: "Saturday: 10AM–4PM",
      },
      faq: {
        badge: "Help Center",
        title: "Frequently Asked Questions",
        desc: "Before reaching out, you might find answers to common questions in our FAQ section.",
        viewFaqs: "View FAQs",
      },
      urgent: {
        badge: "Urgent Support",
        title: "Need Immediate Assistance?",
        desc: "For urgent inquiries or immediate support, please call us directly. Our team is ready to assist you with any questions about bookings, venues, or event planning.",
        callNow: "Call Now",
        emailUs: "Email Us",
      },
    },
    browse: {
      badge: "Discover Venues",
      title: "Browse Halls",
      desc: "Algeria's finest luxury event venues, curated for you",
      searchPh: "Search by name or location...",
      maxPricePh: "Max price (DA)",
      minGuestsPh: "Min guests",
      loading: "Loading venues...",
      noVenues: "No venues found",
      venuesFound: (n: number) => `${n} venue${n !== 1 ? "s" : ""} found`,
      perEvent: "per event",
      viewDetails: "View Details",
    },
    auth: {
      login: {
        title: "Welcome Back",
        subtitle: "Sign in to your account",
        client: "Client",
        owner: "Hall Owner",
        email: "Email Address",
        emailPh: "name@example.com",
        password: "Password",
        forgot: "Forgot?",
        signingIn: "Signing in...",
        signIn: "Sign In",
        noAccount: "Don't have an account?",
        signUp: "Sign Up",
        backHome: "← Back to Home",
      },
      signup: {
        title: "Create Your Account",
        subtitle: "Join Afrahi today",
        client: "Client",
        owner: "Hall Owner",
        fullName: "Full Name",
        fullNamePh: "Your full name",
        email: "Email Address",
        emailPh: "name@example.com",
        password: "Password",
        passwordPh: "Min. 8 characters",
        creating: "Creating account...",
        create: "Create Account",
        hasAccount: "Already have an account?",
        signIn: "Sign In",
        backHome: "← Back to Home",
      },
    },
    sidebar: {
      clientDashboard: "Client Dashboard",
      overview: "Overview",
      wishlist: "Wishlist",
      myReservations: "My Reservations",
      messages: "Messages",
      reviews: "Reviews",
      reportProblem: "Report a Problem",
      logout: "Logout",
    },
    clientDash: {
      welcomeBack: "Welcome Back",
      overviewDesc: "Here's an overview of your reservations",
      pending: "Pending",
      confirmed: "Confirmed",
      favorites: "Favorites",
      total: "Total",
      upcomingReservations: "Upcoming Reservations",
      seeMore: "See More",
      noUpcoming: "No upcoming reservations",
      browseHalls: "Browse Halls",
      discoverHalls: "Discover Halls",
      browseAllHalls: "Browse All Halls",
      exploreDesc: "Explore top-rated halls available for booking",
      noHalls: "No halls available right now",
      guests: "guests",
      bookNow: "Book Now",
      seeMoreBook: "See More & Book a Hall",
      loading: "Loading...",
      confirmed_status: "Confirmed",
    },
    reservationsPage: {
      title: "My Reservations",
      noReservations: "No reservations yet",
      browseHalls: "Browse Halls",
      cancel: "Cancel",
      bookAnother: "Book Another",
      date: "Date",
      guestCount: "Guest Count",
      eventType: "Event Type",
      venuePrice: "Venue Price",
      guests: "guests",
      loading: "Loading...",
      confirmCancel: "Cancel this reservation?",
      reservations: (n: number) => `${n} reservation${n !== 1 ? "s" : ""}`,
    },
    wishlistPage: {
      title: "Favorite Halls",
      subtitle: "Your saved venues for quick booking",
      hall: "hall",
      halls: "halls",
      addMore: "+ Add More",
      noFavorites: "No favorites yet",
      noFavoritesDesc:
        "Start exploring halls and save the ones you love for quick access",
      browseHalls: "Browse Halls",
      loading: "Loading...",
    },
    messagesPage: {
      title: "Messages",
      yourOwners: "Your hall owners",
      yourClients: "Your clients",
      noContacts: "No contacts yet — book a hall first",
      noClientsYet: "No clients yet",
      owner: "Owner",
      client: "Client",
      selectContact: "Select a contact to start chatting",
      selectClient: "Select a client to start chatting",
      noMessages: "No messages yet — say hello! 👋",
      typePlaceholder: "Type a message...",
    },
    reviewsPage: {
      title: "Reviews & Ratings",
      subtitle: "See what others say and share your experience",
      allReviews: "All Reviews",
      myReservations: "My Reservations",
      noReviews: "No reviews yet",
      noReviewsDesc: "Be the first to leave a review!",
      noReservations: "No confirmed reservations",
      noReservationsDesc:
        "After a confirmed reservation you can leave a review here.",
      addReview: "Add Review",
      reviewed: "Reviewed",
      yourRating: "Your Rating",
      yourComment: "Your Comment",
      commentPh: "Share your experience with this hall...",
      submitting: "Submitting...",
      submitReview: "Submit Review",
      cancel: "Cancel",
      loading: "Loading...",
    },
    reportPage: {
      title: "Report a Problem",
      subtitle: "Let us know about any issue and we'll look into it",
      category: "Category",
      technical: "Technical Issue",
      booking: "Booking Problem",
      payment: "Payment Issue",
      owner: "Problem with Owner",
      client: "Problem with Client",
      other: "Other",
      subject: "Subject *",
      subjectPh: "Brief description of the problem",
      description: "Description *",
      descriptionPh: "Describe the problem in detail...",
      fillAll: "Please fill in all fields.",
      failedSubmit: "Failed to submit report. Please try again.",
      submitting: "Submitting...",
      submit: "Submit Report",
      successTitle: "Report Submitted!",
      successDesc:
        "Your report has been sent to our admin team. We'll review it as soon as possible.",
      submitAnother: "Submit Another Report",
      myReports: "My Reports",
      refresh: "Refresh",
      refreshing: "Refreshing...",
      noReports: "No reports submitted yet",
      adminReply: "Admin Reply",
      loading: "Loading...",
      statusPending: "Pending",
      statusReviewed: "Reviewed",
      statusResolved: "Resolved",
    },
    ownerDash: {
      title: "Owner Dashboard",
      subtitle: "Manage your venues and reservations",
      logout: "Logout →",
      myVenues: "My Venues",
      pendingRequests: "Pending Requests",
      confirmed: "Confirmed",
      reviews: "Reviews",
      tabVenues: (n: number) => `My Venues (${n})`,
      tabRequests: (n: number) => `Requests (${n} pending)`,
      tabReviews: (n: number) => `Reviews (${n})`,
      tabMessages: (n: number) => `Messages (${n})`,
      tabAdd: "Add Venue",
      tabEdit: "✏️ Edit Venue",
      noVenues: "No venues yet",
      addFirst: "Add Your First Venue",
      edit: "Edit",
      delete: "Delete",
      guests: "guests",
      price: "Price",
      deleteConfirm: "Delete this venue?",
      reservationRequests: "Reservation Requests",
      pending_badge: "Pending",
      noRequests: "No requests yet",
      noRequestsDesc: "Reservation requests from clients will appear here",
      client: "Client",
      eventDate: "Event Date",
      guests_label: "Guests",
      phone: "Phone",
      accept: "Accept",
      decline: "Decline",
      reservationConfirmed: "Reservation confirmed — client notified",
      requestDeclined: "This request was declined",
      noReviews: "No reviews yet",
      avgRating: "avg",
      noMessages: "No messages yet",
      selectContact: "Select a contact",
      addVenue: "Add New Venue",
      editVenue: "Edit Venue",
      fillDetails: "Fill in the details to list your venue",
      updateDetails: "Update your venue details",
      venueName: "Venue Name",
      venueNamePh: "e.g. Dar El Andalous",
      location: "Location",
      locationPh: "e.g. Algiers, Hussein Dey",
      phone_label: "Phone",
      phonePh: "0550 000 000",
      capacity: "Capacity",
      capacityPh: "e.g. 500",
      priceDa: "Price (DA)",
      pricePh: "e.g. 150000",
      description: "Description",
      descriptionPh: "Describe your venue...",
      venuePhoto: "Venue Photo",
      saving: "Saving...",
      updateVenue: "Update Venue",
      cancel: "Cancel",
      venueAdded: "Venue added successfully!",
      venueUpdated: "Venue updated successfully!",
    },
    adminDash: {
      title: "Admin Dashboard",
      subtitle: "Platform overview and management",
      logout: "Logout →",
      totalUsers: "Total Users",
      totalVenues: "Total Venues",
      totalReservations: "Total Reservations",
      pending: "Pending",
      reviews: "Reviews",
      reports: "Reports",
      allUsers: "All Users",
      manageVenues: "Manage Venues",
      allReservations: "All Reservations",
      tabOverview: "Recent Reservations",
      tabReviews: (n: number) => `Reviews (${n})`,
      tabReports: (n: number, p: number) =>
        `Reports (${n})${p > 0 ? ` • ${p} new` : ""}`,
      recentReservations: "Recent Reservations",
      noReviews: "No reviews yet",
      noReports: "No reports yet",
      replyPh: "Write a reply...",
      resolve: "Resolve",
      markReviewed: "Mark Reviewed",
      adminReply: "Admin Reply",
      loading: "Loading...",
      catTechnical: "Technical Issue",
      catBooking: "Booking Problem",
      catPayment: "Payment Issue",
      catOwner: "Problem with Owner",
      catClient: "Problem with Client",
      catOther: "Other",
    },
    adminUsers: {
      title: "All Users",
      searchPh: "Search by name, email or role...",
      name: "Name",
      email: "Email",
      role: "Role",
      reservations: "Reservations",
      joined: "Joined",
      noUsers: "No users found",
      you: "you",
      loading: "Loading...",
      deleteConfirm: (name: string) =>
        `Delete user "${name}"? This cannot be undone.`,
      users: (n: number) => `${n} user${n !== 1 ? "s" : ""}`,
    },
  },

  ar: {
    nav: {
      home: "الرئيسية",
      browseHalls: "استعراض القاعات",
      about: "من نحن",
      contact: "تواصل معنا",
      login: "تسجيل الدخول",
      getStarted: "ابدأ الآن",
      lang: "English",
    },
    hero: {
      badge: "المنصة الأولى للقاعات في الجزائر",
      title1: "احتفل بأجمل",
      title2: "لحظات حياتك",
      desc: "اكتشف واحجز أفضل قاعات الأفراح الفاخرة في الجزائر للأعراس والاحتفالات والمناسبات التي لا تُنسى.",
      exploreHalls: "استعرض القاعات",
      listVenue: "أضف قاعتك",
    },
    featured: {
      badge: "أفضل الخيارات",
      title: "القاعات الفاخرة المميزة",
      noVenues: "لا توجد قاعات متاحة بعد.",
      guests: "ضيف",
      perEvent: "لكل حفل",
      viewDetails: "عرض التفاصيل",
      seeAll: "← عرض جميع القاعات",
    },
    howItWorks: {
      badge: "خطوات بسيطة",
      title: "كيف يعمل؟",
      steps: [
        {
          title: "تصفح واكتشف",
          desc: "استعرض مجموعتنا المنتقاة من قاعات الأفراح الفاخرة عبر الجزائر",
        },
        {
          title: "قارن واختر",
          desc: "راجع التفاصيل والأسعار والتوافر وسعة الضيوف",
        },
        { title: "احجز واحتفل", desc: "أمّن قاعتك واحتفل بأجمل أيامك" },
      ],
    },
    whyChoose: {
      badge: "لماذا أفراحي",
      title: "لماذا تختار أفراحي",
      features: [
        {
          title: "اختيار مميز",
          desc: "قاعات فاخرة منتقاة بعناية تلبي أعلى معايير الأناقة والخدمة",
        },
        {
          title: "حجز فوري",
          desc: "احجز قاعتك المثالية فورًا بنظام حجز سلس ومبسط",
        },
        {
          title: "أسعار شفافة",
          desc: "أسعار واضحة ومسبقة بدون رسوم خفية أو مفاجآت",
        },
        {
          title: "دعم متخصص",
          desc: "فريق متخصص لمساعدتك في التخطيط لحفلك المثالي",
        },
      ],
    },
    stats: {
      luxuryVenues: "قاعة فاخرة",
      happyClients: "عميل سعيد",
      eventsHosted: "حفل أقيم",
      citiesCovered: "مدينة مشمولة",
    },
    testimonials: {
      badge: "آراء العملاء",
      title: "ماذا يقول عملاؤنا",
      reviews: [
        {
          name: "أمينة بن علي",
          role: "عروس",
          init: "أ",
          quote:
            "أفراحي جعلت يوم زفافنا مثاليًا! كانت عملية الحجز سلسة والقاعة فاقت توقعاتنا.",
        },
        {
          name: "سفيان تومي",
          role: "مدير فعاليات شركات",
          init: "س",
          quote:
            "خدمة احترافية وقاعات رائعة. كان حفلنا السنوي ناجحًا جدًا بفضل أفراحي.",
        },
        {
          name: "مليكة شريف",
          role: "منظمة فعاليات",
          init: "م",
          quote:
            "المنصة سهلة الاستخدام والقاعات من أعلى مستوى. أنصح بها لكل مناسبة خاصة!",
        },
      ],
    },
    readyToBook: {
      badge: "ابدأ اليوم",
      title: "مستعد لحجز قاعة أحلامك؟",
      desc: "انضم إلى آلاف العملاء السعداء الذين وثقوا بنا في أجمل لحظاتهم",
      exploreHalls: "استعرض القاعات",
      createAccount: "إنشاء حساب",
    },
    footer: {
      desc: "منصة حجز قاعات الأفراح الفاخرة للأعراس والاحتفالات واللحظات التي لا تُنسى في الجزائر.",
      quickLinks: "روابط سريعة",
      contact: "تواصل معنا",
      rights: "© 2026 أفراحي. جميع الحقوق محفوظة.",
      links: [
        { label: "الرئيسية", href: "/" },
        { label: "استعراض القاعات", href: "/browse-halls" },
        { label: "من نحن", href: "/about" },
        { label: "تواصل معنا", href: "/contact" },
        { label: "تسجيل الدخول", href: "/login" },
      ],
    },
    about: {
      hero: {
        badge: "قصتنا",
        title: "عن أفراحي",
        desc: "شريكك الموثوق لحجز قاعات الأفراح الفاخرة في الجزائر",
      },
      story: {
        badge: "من نحن",
        title: "قصتنا",
        p1: "تأسست أفراحي بمهمة بسيطة: جعل البحث عن قاعة الأفراح المثالية وحجزها أمرًا سهلًا.",
        p2: "نحن نفهم أن لحظاتك الخاصة تستحق أماكن استثنائية، ونحن هنا لنربطك بأفضل قاعات الأفراح في الجزائر.",
      },
      mission: {
        title: "مهمتنا",
        text: "تبسيط عملية التخطيط للفعاليات من خلال توفير تشكيلة منتقاة من أفضل القاعات، ومعلومات شفافة، وتجارب حجز سلسة لكل احتفال.",
      },
      vision: {
        title: "رؤيتنا",
        text: "أن نصبح المنصة الرائدة في الجزائر لاكتشاف قاعات الفعاليات، ونضع معيار الفخامة والموثوقية والابتكار في قطاع الفعاليات.",
      },
      values: {
        badge: "ما نؤمن به",
        title: "قيمنا",
        subtitle: "المبادئ التي تقود كل ما نقوم به",
        items: [
          {
            title: "التميز",
            desc: "نحافظ على أعلى المعايير في كل قاعة نعرضها",
          },
          {
            title: "الثقة",
            desc: "أسعار شفافة وخدمة صادقة يمكنك الاعتماد عليها",
          },
          {
            title: "الابتكار",
            desc: "نطور منصتنا باستمرار لتحسين تجربة المستخدم",
          },
        ],
      },
      stats: {
        happyClients: "عميل سعيد",
        eventsHosted: "حفل أقيم",
        yearsExperience: "سنة خبرة",
        partnerVenues: "قاعة شريكة",
      },
      cta: {
        title: "مستعد للعثور على قاعتك المثالية؟",
        desc: "انضم إلى آلاف العملاء السعداء الذين وجدوا قاعة أحلامهم مع أفراحي.",
        getStarted: "ابدأ الآن",
        contactUs: "تواصل معنا",
      },
    },
    contact: {
      hero: {
        badge: "نحن هنا من أجلك",
        title: "تواصل معنا",
        desc: "هل لديك أسئلة حول قاعة أو تحتاج مساعدة في التخطيط لحفلك؟ فريقنا هنا لمساعدتك في كل خطوة.",
      },
      form: {
        badge: "راسلنا",
        title: "أرسل لنا رسالة",
        desc: "أكمل النموذج أدناه وسيتواصل معك فريقنا خلال 24 ساعة.",
        firstName: "الاسم الأول",
        firstNamePh: "أدخل اسمك الأول",
        lastName: "اللقب",
        lastNamePh: "أدخل لقبك",
        email: "البريد الإلكتروني",
        emailPh: "بريدك@مثال.com",
        phone: "رقم الهاتف",
        phonePh: "+213 --- --- ---",
        message: "رسالتك",
        messagePh: "كيف يمكننا مساعدتك؟",
        send: "إرسال الرسالة",
      },
      info: {
        phone: "الهاتف",
        email: "البريد الإلكتروني",
        office: "المكتب",
        workingHours: "ساعات العمل",
        officeAddress1: "123 شارع ديدوش مراد",
        officeAddress2: "الجزائر العاصمة 16000، الجزائر",
        hours1: "الأحد–الخميس: 9ص–6م",
        hours2: "السبت: 10ص–4م",
      },
      faq: {
        badge: "مركز المساعدة",
        title: "الأسئلة الشائعة",
        desc: "قبل التواصل، قد تجد إجابات لأسئلة شائعة في قسم الأسئلة الشائعة لدينا.",
        viewFaqs: "عرض الأسئلة الشائعة",
      },
      urgent: {
        badge: "دعم عاجل",
        title: "تحتاج مساعدة فورية؟",
        desc: "للاستفسارات العاجلة أو الدعم الفوري، يرجى الاتصال بنا مباشرة. فريقنا جاهز لمساعدتك في أي أسئلة تتعلق بالحجوزات أو القاعات أو التخطيط للفعاليات.",
        callNow: "اتصل الآن",
        emailUs: "راسلنا",
      },
    },
    browse: {
      badge: "اكتشف القاعات",
      title: "استعرض القاعات",
      desc: "أفضل قاعات الأفراح الفاخرة في الجزائر، منتقاة خصيصًا لك",
      searchPh: "ابحث بالاسم أو الموقع...",
      maxPricePh: "الحد الأقصى للسعر (دج)",
      minGuestsPh: "الحد الأدنى للضيوف",
      loading: "جاري تحميل القاعات...",
      noVenues: "لا توجد قاعات",
      venuesFound: (n: number) => `${n} قاعة وجدت`,
      perEvent: "لكل حفل",
      viewDetails: "عرض التفاصيل",
    },
    auth: {
      login: {
        title: "مرحباً بعودتك",
        subtitle: "سجّل دخولك إلى حسابك",
        client: "عميل",
        owner: "صاحب قاعة",
        email: "البريد الإلكتروني",
        emailPh: "name@example.com",
        password: "كلمة المرور",
        forgot: "نسيت؟",
        signingIn: "جارٍ تسجيل الدخول...",
        signIn: "تسجيل الدخول",
        noAccount: "ليس لديك حساب؟",
        signUp: "إنشاء حساب",
        backHome: "→ العودة للرئيسية",
      },
      signup: {
        title: "إنشاء حسابك",
        subtitle: "انضم إلى أفراحي اليوم",
        client: "عميل",
        owner: "صاحب قاعة",
        fullName: "الاسم الكامل",
        fullNamePh: "اسمك الكامل",
        email: "البريد الإلكتروني",
        emailPh: "name@example.com",
        password: "كلمة المرور",
        passwordPh: "8 أحرف على الأقل",
        creating: "جارٍ إنشاء الحساب...",
        create: "إنشاء الحساب",
        hasAccount: "لديك حساب بالفعل؟",
        signIn: "تسجيل الدخول",
        backHome: "→ العودة للرئيسية",
      },
    },
    sidebar: {
      clientDashboard: "لوحة العميل",
      overview: "نظرة عامة",
      wishlist: "المفضلة",
      myReservations: "حجوزاتي",
      messages: "الرسائل",
      reviews: "التقييمات",
      reportProblem: "الإبلاغ عن مشكلة",
      logout: "تسجيل الخروج",
    },
    clientDash: {
      welcomeBack: "مرحباً بعودتك",
      overviewDesc: "إليك نظرة عامة على حجوزاتك",
      pending: "قيد الانتظار",
      confirmed: "مؤكدة",
      favorites: "المفضلة",
      total: "المجموع",
      upcomingReservations: "الحجوزات القادمة",
      seeMore: "عرض المزيد",
      noUpcoming: "لا توجد حجوزات قادمة",
      browseHalls: "استعرض القاعات",
      discoverHalls: "اكتشف القاعات",
      browseAllHalls: "استعرض جميع القاعات",
      exploreDesc: "استكشف أفضل القاعات المتاحة للحجز",
      noHalls: "لا توجد قاعات متاحة الآن",
      guests: "ضيف",
      bookNow: "احجز الآن",
      seeMoreBook: "عرض المزيد وحجز قاعة",
      loading: "جارٍ التحميل...",
      confirmed_status: "مؤكدة",
    },
    reservationsPage: {
      title: "حجوزاتي",
      noReservations: "لا توجد حجوزات بعد",
      browseHalls: "استعرض القاعات",
      cancel: "إلغاء",
      bookAnother: "احجز مرة أخرى",
      date: "التاريخ",
      guestCount: "عدد الضيوف",
      eventType: "نوع المناسبة",
      venuePrice: "سعر القاعة",
      guests: "ضيف",
      loading: "جارٍ التحميل...",
      confirmCancel: "إلغاء هذا الحجز؟",
      reservations: (n: number) => `${n} حجز`,
    },
    wishlistPage: {
      title: "القاعات المفضلة",
      subtitle: "قاعاتك المحفوظة للحجز السريع",
      hall: "قاعة",
      halls: "قاعات",
      addMore: "+ إضافة المزيد",
      noFavorites: "لا توجد مفضلات بعد",
      noFavoritesDesc: "ابدأ باستكشاف القاعات واحفظ ما تحبه للوصول السريع",
      browseHalls: "استعرض القاعات",
      loading: "جارٍ التحميل...",
    },
    messagesPage: {
      title: "الرسائل",
      yourOwners: "أصحاب القاعات",
      yourClients: "عملاؤك",
      noContacts: "لا توجد جهات اتصال بعد — احجز قاعة أولاً",
      noClientsYet: "لا يوجد عملاء بعد",
      owner: "صاحب القاعة",
      client: "عميل",
      selectContact: "اختر جهة اتصال لبدء المحادثة",
      selectClient: "اختر عميلاً لبدء المحادثة",
      noMessages: "لا توجد رسائل بعد — قل مرحباً! 👋",
      typePlaceholder: "اكتب رسالة...",
    },
    reviewsPage: {
      title: "التقييمات والآراء",
      subtitle: "اطلع على آراء الآخرين وشارك تجربتك",
      allReviews: "جميع التقييمات",
      myReservations: "حجوزاتي",
      noReviews: "لا توجد تقييمات بعد",
      noReviewsDesc: "كن أول من يترك تقييماً!",
      noReservations: "لا توجد حجوزات مؤكدة",
      noReservationsDesc: "بعد حجز مؤكد يمكنك ترك تقييم هنا.",
      addReview: "إضافة تقييم",
      reviewed: "تم التقييم",
      yourRating: "تقييمك",
      yourComment: "تعليقك",
      commentPh: "شارك تجربتك مع هذه القاعة...",
      submitting: "جارٍ الإرسال...",
      submitReview: "إرسال التقييم",
      cancel: "إلغاء",
      loading: "جارٍ التحميل...",
    },
    reportPage: {
      title: "الإبلاغ عن مشكلة",
      subtitle: "أخبرنا بأي مشكلة وسنتعامل معها",
      category: "الفئة",
      technical: "مشكلة تقنية",
      booking: "مشكلة في الحجز",
      payment: "مشكلة في الدفع",
      owner: "مشكلة مع صاحب القاعة",
      client: "مشكلة مع العميل",
      other: "أخرى",
      subject: "الموضوع *",
      subjectPh: "وصف مختصر للمشكلة",
      description: "التفاصيل *",
      descriptionPh: "صف المشكلة بالتفصيل...",
      fillAll: "يرجى ملء جميع الحقول.",
      failedSubmit: "فشل إرسال البلاغ. حاول مرة أخرى.",
      submitting: "جارٍ الإرسال...",
      submit: "إرسال البلاغ",
      successTitle: "تم إرسال البلاغ!",
      successDesc: "تم إرسال بلاغك إلى فريق الإدارة. سنراجعه في أقرب وقت.",
      submitAnother: "إرسال بلاغ آخر",
      myReports: "بلاغاتي",
      refresh: "تحديث",
      refreshing: "جارٍ التحديث...",
      noReports: "لم يتم إرسال أي بلاغات بعد",
      adminReply: "رد الإدارة",
      loading: "جارٍ التحميل...",
      statusPending: "قيد الانتظار",
      statusReviewed: "تمت المراجعة",
      statusResolved: "تم الحل",
    },
    ownerDash: {
      title: "لوحة صاحب القاعة",
      subtitle: "إدارة قاعاتك وحجوزاتك",
      logout: "تسجيل الخروج →",
      myVenues: "قاعاتي",
      pendingRequests: "الطلبات المعلقة",
      confirmed: "مؤكدة",
      reviews: "التقييمات",
      tabVenues: (n: number) => `قاعاتي (${n})`,
      tabRequests: (n: number) => `الطلبات (${n} معلقة)`,
      tabReviews: (n: number) => `التقييمات (${n})`,
      tabMessages: (n: number) => `الرسائل (${n})`,
      tabAdd: "إضافة قاعة",
      tabEdit: "✏️ تعديل القاعة",
      noVenues: "لا توجد قاعات بعد",
      addFirst: "أضف قاعتك الأولى",
      edit: "تعديل",
      delete: "حذف",
      guests: "ضيف",
      price: "السعر",
      deleteConfirm: "حذف هذه القاعة؟",
      reservationRequests: "طلبات الحجز",
      pending_badge: "معلق",
      noRequests: "لا توجد طلبات بعد",
      noRequestsDesc: "طلبات الحجز من العملاء ستظهر هنا",
      client: "العميل",
      eventDate: "تاريخ المناسبة",
      guests_label: "الضيوف",
      phone: "الهاتف",
      accept: "قبول",
      decline: "رفض",
      reservationConfirmed: "تم تأكيد الحجز — تم إخطار العميل",
      requestDeclined: "تم رفض هذا الطلب",
      noReviews: "لا توجد تقييمات بعد",
      avgRating: "متوسط",
      noMessages: "لا توجد رسائل بعد",
      selectContact: "اختر جهة اتصال",
      addVenue: "إضافة قاعة جديدة",
      editVenue: "تعديل القاعة",
      fillDetails: "أدخل التفاصيل لإدراج قاعتك",
      updateDetails: "تحديث تفاصيل قاعتك",
      venueName: "اسم القاعة",
      venueNamePh: "مثال: دار الأندلس",
      location: "الموقع",
      locationPh: "مثال: الجزائر، حسين داي",
      phone_label: "الهاتف",
      phonePh: "0550 000 000",
      capacity: "السعة",
      capacityPh: "مثال: 500",
      priceDa: "السعر (دج)",
      pricePh: "مثال: 150000",
      description: "الوصف",
      descriptionPh: "صف قاعتك...",
      venuePhoto: "صورة القاعة",
      saving: "جارٍ الحفظ...",
      updateVenue: "تحديث القاعة",
      cancel: "إلغاء",
      venueAdded: "تمت إضافة القاعة بنجاح!",
      venueUpdated: "تم تحديث القاعة بنجاح!",
    },
    adminDash: {
      title: "لوحة الإدارة",
      subtitle: "نظرة عامة على المنصة وإدارتها",
      logout: "تسجيل الخروج →",
      totalUsers: "إجمالي المستخدمين",
      totalVenues: "إجمالي القاعات",
      totalReservations: "إجمالي الحجوزات",
      pending: "معلقة",
      reviews: "التقييمات",
      reports: "البلاغات",
      allUsers: "جميع المستخدمين",
      manageVenues: "إدارة القاعات",
      allReservations: "جميع الحجوزات",
      tabOverview: "الحجوزات الأخيرة",
      tabReviews: (n: number) => `التقييمات (${n})`,
      tabReports: (n: number, p: number) =>
        `البلاغات (${n})${p > 0 ? ` • ${p} جديد` : ""}`,
      recentReservations: "الحجوزات الأخيرة",
      noReviews: "لا توجد تقييمات بعد",
      noReports: "لا توجد بلاغات بعد",
      replyPh: "اكتب ردًا...",
      resolve: "حل المشكلة",
      markReviewed: "وضع علامة مراجعة",
      adminReply: "رد الإدارة",
      loading: "جارٍ التحميل...",
      catTechnical: "مشكلة تقنية",
      catBooking: "مشكلة في الحجز",
      catPayment: "مشكلة في الدفع",
      catOwner: "مشكلة مع صاحب القاعة",
      catClient: "مشكلة مع العميل",
      catOther: "أخرى",
    },
    adminUsers: {
      title: "جميع المستخدمين",
      searchPh: "ابحث بالاسم أو البريد أو الدور...",
      name: "الاسم",
      email: "البريد الإلكتروني",
      role: "الدور",
      reservations: "الحجوزات",
      joined: "تاريخ الانضمام",
      noUsers: "لا يوجد مستخدمون",
      you: "أنت",
      loading: "جارٍ التحميل...",
      deleteConfirm: (name: string) =>
        `حذف المستخدم "${name}"؟ لا يمكن التراجع عن هذا.`,
      users: (n: number) => `${n} مستخدم`,
    },
  },
};

interface LangContextType {
  lang: Lang;
  t: typeof translations.en;
  toggleLang: () => void;
  isRTL: boolean;
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  t: translations.en,
  toggleLang: () => {},
  isRTL: false,
});

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");

  useEffect(() => {
    const saved = localStorage.getItem("lang") as Lang;
    if (saved === "en" || saved === "ar") setLang(saved);
  }, []);

  const toggleLang = () => {
    const next: Lang = lang === "en" ? "ar" : "en";
    setLang(next);
    localStorage.setItem("lang", next);
  };

  const isRTL = lang === "ar";
  const t = translations[lang];

  return (
    <LangContext.Provider value={{ lang, t, toggleLang, isRTL }}>
      <div dir={isRTL ? "rtl" : "ltr"} lang={lang}>
        {children}
      </div>
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);

// NOTE: Export additional translations for auth + dashboard
export const authT = {
  en: {
    login: {
      title: "Welcome Back",
      subtitle: "Sign in to your account",
      client: "Client",
      owner: "Hall Owner",
      email: "Email Address",
      password: "Password",
      forgot: "Forgot?",
      signingIn: "Signing in...",
      signIn: "Sign In",
      noAccount: "Don't have an account?",
      signUp: "Sign Up",
      backHome: "← Back to Home",
      error: "Invalid email or password",
    },
    signup: {
      title: "Create Your Account",
      subtitle: "Join Afrahi today",
      client: "Client",
      owner: "Hall Owner",
      fullName: "Full Name",
      fullNamePh: "Your full name",
      email: "Email Address",
      emailPh: "name@example.com",
      password: "Password",
      passwordPh: "Min. 8 characters",
      creating: "Creating account...",
      createAccount: "Create Account",
      haveAccount: "Already have an account?",
      signIn: "Sign In",
      backHome: "← Back to Home",
      error: "Failed to create account",
    },
  },
  ar: {
    login: {
      title: "مرحباً بعودتك",
      subtitle: "سجّل الدخول إلى حسابك",
      client: "عميل",
      owner: "صاحب قاعة",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      forgot: "نسيت؟",
      signingIn: "جاري الدخول...",
      signIn: "تسجيل الدخول",
      noAccount: "ليس لديك حساب؟",
      signUp: "إنشاء حساب",
      backHome: "→ العودة للرئيسية",
      error: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    },
    signup: {
      title: "إنشاء حسابك",
      subtitle: "انضم إلى أفراحي اليوم",
      client: "عميل",
      owner: "صاحب قاعة",
      fullName: "الاسم الكامل",
      fullNamePh: "اسمك الكامل",
      email: "البريد الإلكتروني",
      emailPh: "اسم@مثال.com",
      password: "كلمة المرور",
      passwordPh: "8 أحرف على الأقل",
      creating: "جاري إنشاء الحساب...",
      createAccount: "إنشاء حساب",
      haveAccount: "لديك حساب بالفعل؟",
      signIn: "تسجيل الدخول",
      backHome: "→ العودة للرئيسية",
      error: "فشل إنشاء الحساب",
    },
  },
};

export const dashT = {
  en: {
    sidebar: {
      clientDash: "Client Dashboard",
      overview: "Overview",
      wishlist: "Wishlist",
      reservations: "My Reservations",
      messages: "Messages",
      reviews: "Reviews",
      reportProblem: "Report a Problem",
      logout: "Logout",
    },
    clientHome: {
      welcome: "Welcome Back",
      subtitle: "Here's an overview of your reservations",
      loading: "Loading...",
      pending: "Pending",
      confirmed: "Confirmed",
      favorites: "Favorites",
      total: "Total",
      upcomingRes: "Upcoming Reservations",
      seeMore: "See More",
      noUpcoming: "No upcoming reservations",
      browseHalls: "Browse Halls",
      discoverHalls: "Discover Halls",
      browseAll: "Browse All Halls",
      noHalls: "No halls available right now",
      exploreTopRated: "Explore top-rated halls available for booking",
      guests: "guests",
      bookNow: "Book Now",
      seeMoreBook: "See More & Book a Hall",
      confirmedStatus: "Confirmed",
    },
    reservations: {
      title: "My Reservations",
      loading: "Loading...",
      noReservations: "No reservations yet",
      browseHalls: "Browse Halls",
      date: "Date",
      guestCount: "Guest Count",
      eventType: "Event Type",
      venuePrice: "Venue Price",
      guests: "guests",
      cancel: "Cancel",
      confirmCancel: "Cancel this reservation?",
      bookAnother: "Book Another",
    },
    wishlist: {
      title: "Favorite Halls",
      subtitle: "Your saved venues for quick booking",
      hall: "hall",
      halls: "halls",
      addMore: "+ Add More",
      noFavorites: "No favorites yet",
      noFavoritesDesc:
        "Start exploring halls and save the ones you love for quick access",
      browseHalls: "Browse Halls",
      loading: "Loading...",
    },
    reviews: {
      title: "Reviews & Ratings",
      subtitle: "See what others say and share your experience",
      loading: "Loading...",
      allReviews: "All Reviews",
      myReservations: "My Reservations",
      noReviews: "No reviews yet",
      noReviewsDesc: "Be the first to leave a review!",
      noConfirmed: "No confirmed reservations",
      noConfirmedDesc:
        "After a confirmed reservation you can leave a review here.",
      addReview: "Add Review",
      reviewed: "Reviewed",
      yourRating: "Your Rating",
      yourComment: "Your Comment",
      commentPh: "Share your experience with this hall...",
      submitting: "Submitting...",
      submitReview: "Submit Review",
      cancel: "Cancel",
      errorComment: "Please write a comment before submitting.",
    },
    messages: {
      title: "Messages",
      yourOwners: "Your hall owners",
      yourClients: "Your clients",
      noContacts: "No contacts yet — book a hall first",
      noClients: "No clients yet",
      owner: "Owner",
      client: "Client",
      selectContact: "Select a contact to start chatting",
      selectClient: "Select a client to start chatting",
      noMessages: "No messages yet — say hello! 👋",
      inputPh: "Type a message...",
    },
    report: {
      title: "Report a Problem",
      subtitle: "Let us know about any issue and we'll look into it",
      loading: "Loading...",
      category: "Category",
      technical: "Technical Issue",
      booking: "Booking Problem",
      payment: "Payment Issue",
      ownerProblem: "Problem with Owner",
      clientProblem: "Problem with Client",
      other: "Other",
      subject: "Subject *",
      subjectPh: "Brief description of the problem",
      description: "Description *",
      descriptionPh: "Describe the problem in detail...",
      submitting: "Submitting...",
      submit: "Submit Report",
      successTitle: "Report Submitted!",
      successDesc:
        "Your report has been sent to our admin team. We'll review it as soon as possible.",
      submitAnother: "Submit Another Report",
      myReports: "My Reports",
      refresh: "Refresh",
      refreshing: "Refreshing...",
      noReports: "No reports submitted yet",
      adminReply: "Admin Reply",
      errorFields: "Please fill in all fields.",
      errorFailed: "Failed to submit report. Please try again.",
      statusPending: "Pending",
      statusReviewed: "Reviewed",
      statusResolved: "Resolved",
    },
    owner: {
      title: "Owner Dashboard",
      subtitle: "Manage your venues and reservations",
      logout: "Logout →",
      myVenues: "My Venues",
      pendingRequests: "Pending Requests",
      confirmed: "Confirmed",
      reviews: "Reviews",
      tabVenues: (n: number) => `My Venues (${n})`,
      tabRequests: (n: number) => `Requests (${n} pending)`,
      tabReviews: (n: number) => `Reviews (${n})`,
      tabMessages: (n: number) => `Messages (${n})`,
      tabAdd: "Add Venue",
      tabEdit: "✏️ Edit Venue",
      noVenues: "No venues yet",
      addFirst: "Add Your First Venue",
      edit: "Edit",
      delete: "Delete",
      confirmDelete: "Delete this venue?",
      guests: "guests",
      price: "Price",
      noRequests: "No requests yet",
      noRequestsDesc: "Reservation requests from clients will appear here",
      reservationRequests: "Reservation Requests",
      pending: "Pending",
      client: "Client",
      eventDate: "Event Date",
      guests2: "Guests",
      phone: "Phone",
      accept: "Accept",
      decline: "Decline",
      confirmed2: "Reservation confirmed — client notified",
      declined: "This request was declined",
      noMessages: "No messages yet",
      selectContact: "Select a contact",
      noReviews: "No reviews yet",
      addVenue: "Add New Venue",
      editVenue: "Edit Venue",
      fillDetails: "Fill in the details to list your venue",
      updateDetails: "Update your venue details",
      venueName: "Venue Name",
      venueNamePh: "e.g. Dar El Andalous",
      location: "Location",
      locationPh: "e.g. Algiers, Hussein Dey",
      phone2: "Phone",
      phonePh: "0550 000 000",
      capacity: "Capacity",
      capacityPh: "e.g. 500",
      priceDa: "Price (DA)",
      pricePh: "e.g. 150000",
      description: "Description",
      descriptionPh: "Describe your venue...",
      photo: "Venue Photo",
      saving: "Saving...",
      update: "Update Venue",
      add: "Add Venue",
      cancel: "Cancel",
      addedSuccess: "Venue added successfully!",
      updatedSuccess: "Venue updated successfully!",
    },
    admin: {
      title: "Admin Dashboard",
      subtitle: "Platform overview and management",
      logout: "Logout →",
      totalUsers: "Total Users",
      totalVenues: "Total Venues",
      totalReservations: "Total Reservations",
      pending: "Pending",
      reviews: "Reviews",
      reports: "Reports",
      allUsers: "All Users",
      manageVenues: "Manage Venues",
      allReservations: "All Reservations",
      recentReservations: "Recent Reservations",
      noReviews: "No reviews yet",
      noReports: "No reports yet",
      adminReply: "Admin Reply",
      replyPh: "Write a reply...",
      resolve: "Resolve",
      markReviewed: "Mark Reviewed",
      loading: "Loading...",
      new: "new",
    },
  },
  ar: {
    sidebar: {
      clientDash: "لوحة تحكم العميل",
      overview: "نظرة عامة",
      wishlist: "المفضلة",
      reservations: "حجوزاتي",
      messages: "الرسائل",
      reviews: "التقييمات",
      reportProblem: "الإبلاغ عن مشكلة",
      logout: "تسجيل الخروج",
    },
    clientHome: {
      welcome: "مرحباً بعودتك",
      subtitle: "إليك نظرة عامة على حجوزاتك",
      loading: "جاري التحميل...",
      pending: "قيد الانتظار",
      confirmed: "مؤكد",
      favorites: "المفضلة",
      total: "المجموع",
      upcomingRes: "الحجوزات القادمة",
      seeMore: "عرض المزيد",
      noUpcoming: "لا توجد حجوزات قادمة",
      browseHalls: "استعرض القاعات",
      discoverHalls: "اكتشف القاعات",
      browseAll: "استعرض جميع القاعات",
      noHalls: "لا توجد قاعات متاحة الآن",
      exploreTopRated: "استعرض أفضل القاعات المتاحة للحجز",
      guests: "ضيف",
      bookNow: "احجز الآن",
      seeMoreBook: "عرض المزيد وحجز قاعة",
      confirmedStatus: "مؤكد",
    },
    reservations: {
      title: "حجوزاتي",
      loading: "جاري التحميل...",
      noReservations: "لا توجد حجوزات بعد",
      browseHalls: "استعرض القاعات",
      date: "التاريخ",
      guestCount: "عدد الضيوف",
      eventType: "نوع الحفل",
      venuePrice: "سعر القاعة",
      guests: "ضيف",
      cancel: "إلغاء",
      confirmCancel: "هل تريد إلغاء هذا الحجز؟",
      bookAnother: "احجز مرة أخرى",
    },
    wishlist: {
      title: "القاعات المفضلة",
      subtitle: "القاعات المحفوظة للحجز السريع",
      hall: "قاعة",
      halls: "قاعات",
      addMore: "+ إضافة المزيد",
      noFavorites: "لا توجد مفضلة بعد",
      noFavoritesDesc: "ابدأ باستعراض القاعات واحفظ ما يعجبك للوصول السريع",
      browseHalls: "استعرض القاعات",
      loading: "جاري التحميل...",
    },
    reviews: {
      title: "التقييمات والآراء",
      subtitle: "اقرأ آراء الآخرين وشارك تجربتك",
      loading: "جاري التحميل...",
      allReviews: "جميع التقييمات",
      myReservations: "حجوزاتي",
      noReviews: "لا توجد تقييمات بعد",
      noReviewsDesc: "كن أول من يترك تقييماً!",
      noConfirmed: "لا توجد حجوزات مؤكدة",
      noConfirmedDesc: "بعد الحجز المؤكد يمكنك ترك تقييم هنا.",
      addReview: "إضافة تقييم",
      reviewed: "تم التقييم",
      yourRating: "تقييمك",
      yourComment: "تعليقك",
      commentPh: "شارك تجربتك مع هذه القاعة...",
      submitting: "جاري الإرسال...",
      submitReview: "إرسال التقييم",
      cancel: "إلغاء",
      errorComment: "الرجاء كتابة تعليق قبل الإرسال.",
    },
    messages: {
      title: "الرسائل",
      yourOwners: "أصحاب القاعات",
      yourClients: "عملاؤك",
      noContacts: "لا توجد جهات اتصال — احجز قاعة أولاً",
      noClients: "لا يوجد عملاء بعد",
      owner: "صاحب قاعة",
      client: "عميل",
      selectContact: "اختر جهة اتصال لبدء المحادثة",
      selectClient: "اختر عميلاً لبدء المحادثة",
      noMessages: "لا توجد رسائل بعد — قل مرحباً! 👋",
      inputPh: "اكتب رسالة...",
    },
    report: {
      title: "الإبلاغ عن مشكلة",
      subtitle: "أخبرنا عن أي مشكلة وسنتولى الأمر",
      loading: "جاري التحميل...",
      category: "الفئة",
      technical: "مشكلة تقنية",
      booking: "مشكلة في الحجز",
      payment: "مشكلة في الدفع",
      ownerProblem: "مشكلة مع صاحب القاعة",
      clientProblem: "مشكلة مع عميل",
      other: "أخرى",
      subject: "الموضوع *",
      subjectPh: "وصف مختصر للمشكلة",
      description: "الوصف *",
      descriptionPh: "صف المشكلة بالتفصيل...",
      submitting: "جاري الإرسال...",
      submit: "إرسال البلاغ",
      successTitle: "تم إرسال البلاغ!",
      successDesc: "تم إرسال بلاغك إلى فريق الإدارة. سنراجعه في أقرب وقت.",
      submitAnother: "إرسال بلاغ آخر",
      myReports: "بلاغاتي",
      refresh: "تحديث",
      refreshing: "جاري التحديث...",
      noReports: "لا توجد بلاغات بعد",
      adminReply: "رد الإدارة",
      errorFields: "الرجاء تعبئة جميع الحقول.",
      errorFailed: "فشل إرسال البلاغ. حاول مرة أخرى.",
      statusPending: "قيد الانتظار",
      statusReviewed: "تمت المراجعة",
      statusResolved: "تم الحل",
    },
    owner: {
      title: "لوحة تحكم صاحب القاعة",
      subtitle: "إدارة قاعاتك وحجوزاتك",
      logout: "← تسجيل الخروج",
      myVenues: "قاعاتي",
      pendingRequests: "الطلبات المعلقة",
      confirmed: "مؤكدة",
      reviews: "تقييمات",
      tabVenues: (n: number) => `قاعاتي (${n})`,
      tabRequests: (n: number) => `الطلبات (${n} معلق)`,
      tabReviews: (n: number) => `التقييمات (${n})`,
      tabMessages: (n: number) => `الرسائل (${n})`,
      tabAdd: "إضافة قاعة",
      tabEdit: "✏️ تعديل القاعة",
      noVenues: "لا توجد قاعات بعد",
      addFirst: "أضف قاعتك الأولى",
      edit: "تعديل",
      delete: "حذف",
      confirmDelete: "هل تريد حذف هذه القاعة؟",
      guests: "ضيف",
      price: "السعر",
      noRequests: "لا توجد طلبات بعد",
      noRequestsDesc: "ستظهر هنا طلبات الحجز من العملاء",
      reservationRequests: "طلبات الحجز",
      pending: "معلق",
      client: "العميل",
      eventDate: "تاريخ الحفل",
      guests2: "الضيوف",
      phone: "الهاتف",
      accept: "قبول",
      decline: "رفض",
      confirmed2: "تم تأكيد الحجز — تم إشعار العميل",
      declined: "تم رفض هذا الطلب",
      noMessages: "لا توجد رسائل بعد",
      selectContact: "اختر جهة اتصال",
      noReviews: "لا توجد تقييمات بعد",
      addVenue: "إضافة قاعة جديدة",
      editVenue: "تعديل القاعة",
      fillDetails: "أدخل تفاصيل القاعة لإدراجها",
      updateDetails: "حدّث تفاصيل قاعتك",
      venueName: "اسم القاعة",
      venueNamePh: "مثال: دار الأندلس",
      location: "الموقع",
      locationPh: "مثال: الجزائر، حسين داي",
      phone2: "الهاتف",
      phonePh: "0550 000 000",
      capacity: "السعة",
      capacityPh: "مثال: 500",
      priceDa: "السعر (دج)",
      pricePh: "مثال: 150000",
      description: "الوصف",
      descriptionPh: "صف قاعتك...",
      photo: "صورة القاعة",
      saving: "جاري الحفظ...",
      update: "تحديث القاعة",
      add: "إضافة القاعة",
      cancel: "إلغاء",
      addedSuccess: "تمت إضافة القاعة بنجاح!",
      updatedSuccess: "تم تحديث القاعة بنجاح!",
    },
    admin: {
      title: "لوحة تحكم الإدارة",
      subtitle: "نظرة عامة وإدارة المنصة",
      logout: "← تسجيل الخروج",
      totalUsers: "إجمالي المستخدمين",
      totalVenues: "إجمالي القاعات",
      totalReservations: "إجمالي الحجوزات",
      pending: "معلق",
      reviews: "تقييمات",
      reports: "بلاغات",
      allUsers: "جميع المستخدمين",
      manageVenues: "إدارة القاعات",
      allReservations: "جميع الحجوزات",
      recentReservations: "أحدث الحجوزات",
      noReviews: "لا توجد تقييمات بعد",
      noReports: "لا توجد بلاغات بعد",
      adminReply: "رد الإدارة",
      replyPh: "اكتب رداً...",
      resolve: "حل",
      markReviewed: "تحديد كمراجع",
      loading: "جاري التحميل...",
      new: "جديد",
    },
  },
};
// This file is already complete above - we need to add auth and dashboard translations
